/**
 * Translations for <FormSelect>/<FormSelectMultiple>.
 *
 * Deliberately NOT part of the auto-generated `../../strings/translations.ts`
 * (that file is regenerated by the fireback language & translation manager
 * from the app's own `strings-*.yml` catalog and shouldn't be hand-edited,
 * and pulling from it means every consumer of FormSelect - including ones
 * outside this app entirely - inherits that whole catalog and its `useS`/
 * locale-context wiring just to render a select box). Keeping this
 * component's strings local to its own folder, resolved from a plain
 * `locale` prop instead, is what lets FormSelect be used standalone.
 */

import { createContext, useContext } from "react";

/**
 * Optional escape hatch from passing `locale` to every single `<FormSelect>`
 * by hand: mount `<FormSelectLocaleProvider value={locale}>` once near your
 * app's root, and any `<FormSelect>` under it that doesn't set its own
 * `locale` prop picks this up instead. Left unmounted,
 * `useFormSelectLocale()` simply returns `undefined` and
 * `resolveFormSelectStrings` falls back to its own default ("en") exactly as
 * if this context didn't exist - so FormSelect never *requires* it, and
 * still doesn't depend on the app's own `useS`/locale-context machinery, or
 * any particular way of tracking "the current locale", to work standalone.
 */
const FormSelectLocaleContext = createContext<string | undefined>(undefined);

export const FormSelectLocaleProvider = FormSelectLocaleContext.Provider;

/** The locale set by an ancestor `<FormSelectLocaleProvider>`, if any. */
export function useFormSelectLocale(): string | undefined {
  return useContext(FormSelectLocaleContext);
}

export interface FormSelectStrings {
  /** Shown instead of the control when no `querySource` was given. */
  noQuerySourceToRender: string;
  /** aria-label on the native <select> fallback (`convertToNative`). */
  defaultSelectExample: string;
  /** First, unselectable option of the native <select> fallback. */
  selectPlaceholder: string;
  /** Placeholder text of the react-select search box. */
  searchPlaceholder: string;
  /** react-select's "nothing matched" message. */
  noOptions: string;
}

export const en: FormSelectStrings = {
  noQuerySourceToRender: "No query source to render",
  defaultSelectExample: "Default select example",
  selectPlaceholder: "- Select an option -",
  searchPlaceholder: "Search...",
  noOptions: "No options",
};

export const de: FormSelectStrings = {
  noQuerySourceToRender: "Keine Abfragequelle zum Anzeigen vorhanden",
  defaultSelectExample: "Standardauswahlbeispiel",
  selectPlaceholder: "- Option auswählen -",
  searchPlaceholder: "Suchen...",
  noOptions: "Keine Optionen",
};

export const es: FormSelectStrings = {
  noQuerySourceToRender: "No hay fuente de consulta para mostrar",
  defaultSelectExample: "Ejemplo de selección predeterminada",
  selectPlaceholder: "- Selecciona una opción -",
  searchPlaceholder: "Buscar...",
  noOptions: "Sin opciones",
};

export const fa: FormSelectStrings = {
  noQuerySourceToRender: "منبعی برای نمایش وجود ندارد",
  defaultSelectExample: "نمونه انتخاب پیش‌فرض",
  selectPlaceholder: "- یک گزینه را انتخاب کنید -",
  searchPlaceholder: "جستجو...",
  noOptions: "هیچ گزینه‌ای وجود ندارد",
};

export const ru: FormSelectStrings = {
  noQuerySourceToRender: "Нет источника запроса для отображения",
  defaultSelectExample: "Пример выбора по умолчанию",
  selectPlaceholder: "- Выберите вариант -",
  searchPlaceholder: "Поиск...",
  noOptions: "Нет вариантов",
};

export const pl: FormSelectStrings = {
  noQuerySourceToRender: "Brak źródła zapytania do wyświetlenia",
  defaultSelectExample: "Domyślny przykład wyboru",
  selectPlaceholder: "- Wybierz opcję -",
  searchPlaceholder: "Szukaj...",
  noOptions: "Brak opcji",
};

export const fr: FormSelectStrings = {
  noQuerySourceToRender: "Aucune source de requête à afficher",
  defaultSelectExample: "Exemple de sélection par défaut",
  selectPlaceholder: "- Sélectionner une option -",
  searchPlaceholder: "Rechercher...",
  noOptions: "Aucune option",
};

/** Every locale FormSelect ships copy for out of the box, keyed by 2-char code. */
export const formSelectStrings: Record<string, FormSelectStrings> = {
  en,
  de,
  es,
  fa,
  ru,
  pl,
  fr,
};

/** Locales this component ships copy for. */
export const FORM_SELECT_LOCALES = Object.keys(
  formSelectStrings,
) as Array<keyof typeof formSelectStrings>;

/**
 * Resolves the strings FormSelect should render: the built-in copy for
 * `locale` (falling back to English for an unset/unrecognized 2-char code),
 * with `overrides` shallow-merged on top so a caller can replace one key or
 * hand in a whole custom, fully-typed translation map - `Partial` keeps
 * every key optional while still catching a typo'd key or wrong value type
 * at compile time. No `useS`/locale-context dependency involved.
 */
export function resolveFormSelectStrings(
  locale?: string,
  overrides?: Partial<FormSelectStrings>,
): FormSelectStrings {
  const base =
    formSelectStrings[(locale || "en").toLowerCase()] ?? formSelectStrings.en;
  return overrides ? { ...base, ...overrides } : base;
}
